# Site settings
url: "the-safety.de"
baseurl: ""
title: "Dost International Training Center"
description: "Wind Energy Training and Certification"
keywords: "Training, GWO, IRATA, Wind"

organisation: "Dost International Training Center"
organisation_address_office: "Wullener Feld 61, 58454 Witten, Germany"
organisation_address_facility: "Westerweide 27, 58456 Witten, Germany"
organisation_email: "training@dostgroup.de"
organisation_phone: "+49 2302 282361 - 0"

nav_logo: "dost-logo-bold-borderless.svg"

# For Impressum
corporate_name: "Dost GmbH"
corporate_address: "Wullener Feld 61, 58454 Witten, Germany"
corporate_ceo: "Mehmet Sar"
corporate_phone: "+49 (0) 2302 28 23 61 0"
corporate_fax: "+49 (0) 2302 28 23 61 23"
corporate_email: "training@dostgroup.de"
corporate_registration: "HRB10550"
corporate_jurisdiction: "Bochum"
corporate_vat_no: "DE242801578"

maps_link_office: "https://goo.gl/maps/g1NmMiSCfFRtmr538"
maps_embed_office: "https://maps.google.com/maps?&hl=en&q=Wullener%20Feld%2061,%2058454%20Witten,%20Germany+(Dost%20Group%20Offices)&t=&z=15&ie=UTF8&iwloc=B&output=embed"

maps_link_facility: "https://goo.gl/maps/ZB33eSXNRrRtHdZx6"
maps_embed_facility: "https://maps.google.com/maps?hl=en&q=Westerweide%2027,%2058456%20Witten,%20Germany+(Dost%20Group%20Facility)&t=&z=15&ie=UTF8&iwloc=B&output=embed"

google_analytics: "UA-180935645-1"

verification_url: "https://training.dostgroup.de/verify"

collections:
  courses:
    output: true
  courses_de:
    output: true
    permalink: /de/courses/:path/

defaults:
  - scope:
      path: ""
      type: "courses"
    values:
      layout: "course"
  - scope:
      path: ""
      type: "courses_de"
    values:
      layout: "course"

exclude:
  - README.md

# Build settings
markdown: kramdown
permalink: pretty

sass:
  style: compressed

#host: localhost
