# Site settings
url: "dost-training.github.io"
baseurl: "/"
title: "Dost Training Center"
description: "Wind Energy and Industrial Rope Access Training and Certification"

organisation: "Dost Training Center"

# Build settings
markdown: kramdown
permalink: pretty

sass:
  style: compressed

#host: localhost
