# Site settings
url: "training.dostgroup.de"
baseurl: "/"
title: "Dost Wind Training Center"
description: "Wind Energy and Industrial Rope Access Training and Certification"

organisation: "Dost Wind Training Center"

# Build settings
markdown: kramdown
permalink: pretty

sass:
  style: compressed

#host: localhost
