# Site settings
url: "dost-training.github.io"
baseurl: "/"
title: "Dost Wind Training Center"
description: "Wind Energy and Industrial Rope Access Training and Certification"

organisation: "Dost Wind Training Center"
address: "Westerweide 27, 58456 Witten, Germany"

# Build settings
markdown: kramdown
permalink: pretty

sass:
  style: compressed

#host: localhost
